services:
  neon_local:
    build: app/
    ports:
      - "5432:5432"
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      PARENT_BRANCH_ID: ${PARENT_BRANCH_ID}
      #BRANCH_ID: br-dark-bar-a440iizf
      #DELETE_BRANCH: < True | False >
      #DRIVER: < postgres | serverless >
    #volumes:
    #  - ./.neon_local/:/tmp/.neon_local
    #  - ../.git/HEAD:/tmp/.git/HEAD:ro,consistent