name: Build and Push neon-proxy Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ghcr-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push neon-multi-proxy Docker Image to GHCR
        uses: docker/build-push-action@v6
        with:
          file: app/Dockerfile
          context: ./app
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          pull: true
          tags: |
            ghcr.io/neondatabase-labs/neon_local:latest
            ghcr.io/neondatabase-labs/neon_local:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title="Neon Local Proxy Container"
            org.opencontainers.image.description="Local proxy for Neon Databases"
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Log out from GHCR
        run: docker logout ghcr.io

  dockerhub-push:
    needs: ghcr-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.NEON_LOCAL_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_LOCAL_DOCKERHUB_PASSWORD }}

      - name: Build and push multi-arch image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            neondatabase/neon_local:latest
            neondatabase/neon_local:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Encode README content
        id: readme
        run: jq -Rs . < README.md > encoded-readme.json

      - name: Get Docker Hub token
        id: dockerhub_login
        env:
          DOCKERHUB_USERNAME: ${{ vars.NEON_LOCAL_DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.NEON_LOCAL_DOCKERHUB_PASSWORD }}
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST -d "{\"username\": \"${DOCKERHUB_USERNAME}\", \"password\": \"${DOCKERHUB_PASSWORD}\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)

          echo "token=$TOKEN" >> $GITHUB_OUTPUT
          echo "Docker token length: ${#{{ steps.dockerhub_login.outputs.token }}}"




      - name: Update Docker Hub description
        run: |
          curl -s -X PATCH https://hub.docker.com/v2/repositories/neondatabase/neon_local/ \
            -H "Authorization: JWT ${{ steps.dockerhub_login.outputs.token }}" \
            -H "Content-Type: application/json" \
            --data "@encoded-readme.json"

